#!/sbin/openrc-run
# Copyright 1999-2017 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2

: ${VALKEY_DIR:=/var/lib/valkey}
: ${VALKEY_CONF:=/etc/valkey/valkey.conf}
: ${VALKEY_OPTS:="${VALKEY_CONF}"}
: ${VALKEY_USER:=valkey}
: ${VALKEY_GROUP:=valkey}
: ${VALKEY_TIMEOUT:=30}

# https://bugs.gentoo.org/631002#c10
# Force '--daemonize no' to override the config file
command="/usr/sbin/valkey-server"
command_args="${VALKEY_OPTS} --daemonize no"
command_background="true"
command_user="${VALKEY_USER}:${VALKEY_GROUP}"
pidfile="/run/${RC_SVCNAME}.pid"
retry="${VALKEY_TIMEOUT}"
start_stop_daemon_args="--chdir \"${VALKEY_DIR}\""

depend() {
	use localmount logger
	after keepalived
}
